/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_rotation_free(a: number, b: number): void;
export function rotation_new(a: number, b: number, c: number, d: number): number;
export function rotation_default(): number;
export function rotation_x(a: number): number;
export function rotation_y(a: number): number;
export function rotation_z(a: number): number;
export function rotation_w(a: number): number;
export function __wbg_posesolverresult_free(a: number, b: number): void;
export function __wbg_get_posesolverresult_upper_body(a: number): number;
export function __wbg_set_posesolverresult_upper_body(a: number, b: number): void;
export function __wbg_get_posesolverresult_lower_body(a: number): number;
export function __wbg_set_posesolverresult_lower_body(a: number, b: number): void;
export function __wbg_get_posesolverresult_neck(a: number): number;
export function __wbg_set_posesolverresult_neck(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_hip(a: number): number;
export function __wbg_set_posesolverresult_left_hip(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_hip(a: number): number;
export function __wbg_set_posesolverresult_right_hip(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_foot(a: number): number;
export function __wbg_set_posesolverresult_left_foot(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_foot(a: number): number;
export function __wbg_set_posesolverresult_right_foot(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_upper_arm(a: number): number;
export function __wbg_set_posesolverresult_left_upper_arm(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_upper_arm(a: number): number;
export function __wbg_set_posesolverresult_right_upper_arm(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_lower_arm(a: number): number;
export function __wbg_set_posesolverresult_left_lower_arm(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_lower_arm(a: number): number;
export function __wbg_set_posesolverresult_right_lower_arm(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_wrist(a: number): number;
export function __wbg_set_posesolverresult_left_wrist(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_wrist(a: number): number;
export function __wbg_set_posesolverresult_right_wrist(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_thumb_cmc(a: number): number;
export function __wbg_set_posesolverresult_left_thumb_cmc(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_thumb_mcp(a: number): number;
export function __wbg_set_posesolverresult_left_thumb_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_index_finger_mcp(a: number): number;
export function __wbg_set_posesolverresult_left_index_finger_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_index_finger_pip(a: number): number;
export function __wbg_set_posesolverresult_left_index_finger_pip(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_index_finger_dip(a: number): number;
export function __wbg_set_posesolverresult_left_index_finger_dip(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_middle_finger_mcp(a: number): number;
export function __wbg_set_posesolverresult_left_middle_finger_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_middle_finger_pip(a: number): number;
export function __wbg_set_posesolverresult_left_middle_finger_pip(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_middle_finger_dip(a: number): number;
export function __wbg_set_posesolverresult_left_middle_finger_dip(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_ring_finger_mcp(a: number): number;
export function __wbg_set_posesolverresult_left_ring_finger_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_ring_finger_pip(a: number): number;
export function __wbg_set_posesolverresult_left_ring_finger_pip(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_ring_finger_dip(a: number): number;
export function __wbg_set_posesolverresult_left_ring_finger_dip(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_pinky_finger_mcp(a: number): number;
export function __wbg_set_posesolverresult_left_pinky_finger_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_pinky_finger_pip(a: number): number;
export function __wbg_set_posesolverresult_left_pinky_finger_pip(a: number, b: number): void;
export function __wbg_get_posesolverresult_left_pinky_finger_dip(a: number): number;
export function __wbg_set_posesolverresult_left_pinky_finger_dip(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_thumb_cmc(a: number): number;
export function __wbg_set_posesolverresult_right_thumb_cmc(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_thumb_mcp(a: number): number;
export function __wbg_set_posesolverresult_right_thumb_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_index_finger_mcp(a: number): number;
export function __wbg_set_posesolverresult_right_index_finger_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_index_finger_pip(a: number): number;
export function __wbg_set_posesolverresult_right_index_finger_pip(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_index_finger_dip(a: number): number;
export function __wbg_set_posesolverresult_right_index_finger_dip(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_middle_finger_mcp(a: number): number;
export function __wbg_set_posesolverresult_right_middle_finger_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_middle_finger_pip(a: number): number;
export function __wbg_set_posesolverresult_right_middle_finger_pip(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_middle_finger_dip(a: number): number;
export function __wbg_set_posesolverresult_right_middle_finger_dip(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_ring_finger_mcp(a: number): number;
export function __wbg_set_posesolverresult_right_ring_finger_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_ring_finger_pip(a: number): number;
export function __wbg_set_posesolverresult_right_ring_finger_pip(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_ring_finger_dip(a: number): number;
export function __wbg_set_posesolverresult_right_ring_finger_dip(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_pinky_finger_mcp(a: number): number;
export function __wbg_set_posesolverresult_right_pinky_finger_mcp(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_pinky_finger_pip(a: number): number;
export function __wbg_set_posesolverresult_right_pinky_finger_pip(a: number, b: number): void;
export function __wbg_get_posesolverresult_right_pinky_finger_dip(a: number): number;
export function __wbg_set_posesolverresult_right_pinky_finger_dip(a: number, b: number): void;
export function __wbg_posesolver_free(a: number, b: number): void;
export function posesolver_new(): number;
export function posesolver_solve(a: number, b: number, c: number, d: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_exn_store(a: number): void;
